[workspace]
channels = ["conda-forge"]
name = "SIF_downscaling_CDSE"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
ipykernel = ">=7.1.0,<8"
openeo = ">=0.46.0,<0.47"
rioxarray = ">=0.20.0,<0.21"
pystac = ">=1.14.1,<2"
shapely = ">=2.1.2,<3"
xarray = ">=2025.1.1,<2026"
matplotlib = ">=3.10.8,<4"
xesmf = ">=0.8.7,<0.10"
numpy = ">=2.3.5,<3"
cartopy = ">=0.25.0,<0.26"
netcdf4 = ">=1.7.2,<2"
zarr = ">=3.1.5,<4"
quarto = ">=1.8.26,<2"
nbformat = ">=5.10.4,<6"
nbclient = ">=0.10.2,<0.11"
